name: markdown-linter

on:
  push:
    branches:
      - main
    paths:
      - "**.md"
      - .github/workflows/markdown-linter.yml

jobs:
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Lint
        uses: ruzickap/action-my-markdown-linter@v1
        with:
          exclude: |
            unorganized_documents/*
            files/*
            CHANGELOG.md
      - name: Markdown Lint using pre-built container
        uses: docker://peru/my-markdown-linter
        with:
          exclude: |
            unorganized_documents/*
            files/*
            CHANGELOG.md
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link Checker
        uses: ruzickap/action-my-markdown-link-checker@v1
        with:
          exclude: |
            unorganized_documents/*
            files/*
            CHANGELOG.md
