name: markdown-linter

on:
  push:
    paths: "**/*.md"

jobs:
  linting:
    name: "Markdown linting"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1
          with:
          rules: "./.markdownlintrc"
          args: "**/*.md"
          ignore: "./CHANGELOG.md"
